### ISSUE TITLE
URL for aneu_proc.tar.gz & aneu_raw.tar.gz data not working.

### ISSUE THREAD

**Issue by JasperBoom** [MarioniLab/Aneuploidy2017#1]
Good day!

I am trying to run through the scripts from your paper. The data links described in `get_data.sh` don’t seem to work anymore. Is that data still available somewhere?

Kind regards,
Jasper

**Comment by jonathangriffiths** [comment]
Hi there,

It does look like the gitlab server has been closed. Unfortunately I won't be able to help you out with getting the data myself, because I have long lost access to the lab servers. If you really want these data, we will need to get in touch with someone in John's lab who still has EBI access.

Do you want to proceed with that? The reason that I ask is that the methods in this paper have been quite substantially superseded by better approaches, so you might be better-served by starting with them.

Jonny

**Comment by JasperBoom** [comment]
> Hi there,
> 
> It does look like the gitlab server has been closed. Unfortunately I won't be able to help you out with getting the data myself, because I have long lost access to the lab servers. If you really want these data, we will need to get in touch with someone in John's lab who still has EBI access.
> 
> Do you want to proceed with that? The reason that I ask is that the methods in this paper have been quite substantially superseded by better approaches, so you might be better-served by starting with them.
> 
> Jonny

Hello Jonathan,

Thank you for your quick response! We are quite interested in these other approaches you mentioned, would you be willing to elaborate a little on that? We are currently also looking into the method by Starostik et al. 2020 [10.1101/gr.262774.120], which also used this dataset in their analysis, which is another reason I was looking into the data.

You mentioned we would have to contact someone at John Marioni’s group. Would you be willing to share contact details for them, if you have them? The dataset might be of interest regardless of this specific method.

Kind regards,
Jasper

**Comment by jonathangriffiths** [comment]
That paper is one I saw that seemed to be able to get something out of the human embryo dataset, which I found too noisy for my method. The only other I have seen was at ASHG 2019, which just used my approach plus smoothing, which seemed to help. I'm afraid I don't know much more that is specific than those two examples.

You should email marioni@ebi.ac.uk

Jonny

**Comment by JasperBoom** [comment]
> That paper is one I saw that seemed to be able to get something out of the human embryo dataset, which I found too noisy for my method. The only other I have seen was at ASHG 2019, which just used my approach plus smoothing, which seemed to help. I'm afraid I don't know much more that is specific than those two examples.
> 
> You should email [marioni@ebi.ac.uk](mailto:marioni@ebi.ac.uk)
> 
> Jonny

Alright! Thank you for your help!
