### ISSUE TITLE
Minimum number of genes used

### ISSUE THREAD

**Issue by dongjuleem** [MarioniLab/Aneuploidy2017#3]
Thank you for providing the great tool. While using the tool, after performing scploid, information on certain chromosomes disappeared. The anticipated cause appears to be that the number of genes used for the chromosomes that disappeared was too few. 
Is there a **minimum number of genes required** when considering whether a specific chromosome is aneuploid?

**Code**
```
 ploidytest = makeAneu(counts = as.matrix(filtered_fetal_counts), 
                        genes = filtered_fetal_annotation$ensembl_gene_id, 
                        chrs = filtered_fetal_annotation$chromosome_name, 
                        cellNames = colnames(filtered_fetal_counts), 
                        cellGroups = rep(samplename, ncol(filtered_fetal_counts)))

  expression_results <- calcAneu(ploidytest) %>% as.data.table()
```

**Issue in chr18 and chr21**
```
> unique(ploidytest@chrs)
 [1] "2"  "3"  "1"  "4"  "7"  "6"  "8"  "9"  "5"  "16" "13" "12" "10" "11" "15"
[16] "14" "17" "19" "18" "22" "20" "21"
> unique(expression_results$chr)
 [1]  1 10 11 12 13 14 15 16 17 19  2 20 22  3  4  5  6  7  8  9
```

**Anticipated cause(number of genes was too few)**
```
> sum(filtered_fetal_annotation$chromosome_name == 17)
[1] 42
> sum(filtered_fetal_annotation$chromosome_name == 18)
[1] 9
> sum(filtered_fetal_annotation$chromosome_name == 19)
[1] 58
> sum(filtered_fetal_annotation$chromosome_name == 20)
[1] 22
> sum(filtered_fetal_annotation$chromosome_name == 21)
[1] 12
```

**Comment by jonathangriffiths** [comment]
Hi,

I'm afraid I don't really remember much about this 7 year old tool!

I wonder if you don't have any highly expressed genes remaining at all on these chromosomes (this line https://github.com/MarioniLab/Aneuploidy2017/blob/286c064bce53ccd55c2d1a600abd12a84f655328/package/R/methods.R#L62)

Jonny
